export const GET_RECENT_LAWLIST_REQUEST = "GET_RECENT_LAWLIST_REQUEST";
export const GET_RECENT_LAWLIST_SUCCESS = "GET_RECENT_LAWLIST_SUCCESS";
export const GET_RECENT_LAWLIST_FAILURE = "GET_RECENT_LAWLIST_FAILURE";

export const GET_DETAIL_LAWDATA_REQUEST = "GET_DETAIL_LAWDATA_REQUEST";
export const GET_DETAIL_LAWDATA_SUCCESS = "GET_DETAIL_LAWDATA_SUCCESS";
export const GET_DETAIL_LAWDATA_FAILURE = "GET_DETAIL_LAWDATA_FAILURE";

export const QUERYING_LAWLIST_REQUEST = "QUERYING_LAWLIST_REQUEST";
export const QUERYING_LAWLIST_SUCCESS = "QUERYING_LAWLIST_SUCCESS";
export const QUERYING_LAWLIST_FAILURE = "QUERYING_LAWLIST_FAILURE";
